parameters:
  - name: Environment
    type: string
    default: prd
    displayName: Environment specification
    values:
      - prd

trigger: none

variables:
- group: default
- name: version.MajorMinor
  value: '0.1' # Manually adjust the version number as needed for semantic versioning. Revision is auto-incremented.
- name: version.Revision
  value: $[counter(variables['version.MajorMinor'], 0)]
- name: versionNumber
  value: $[format('{0}.{1}', variables['version.MajorMinor'], variables['version.Revision'])]


name: $(versionNumber)


pool:
 vmImage: ubuntu-latest

resources:
 repositories:
   - repository: templates
     type : git
     name : cxi-build-templates


stages:
 - stage: Build
   displayName: Build images
   jobs:
    - job: Build
      displayName: Build images
      steps:
      - task: Docker@2
        displayName: Build an image partner-profile
        inputs:
          containerRegistry: 'ado-2-acr-prd'
          repository: 'cxi-cdp-customer-profiles-partner-profile'
          command: 'build'
          Dockerfile: '**/Dockerfile'
          buildContext: '$(Build.SourcesDirectory)/src/'
          tags: |
            $(Build.BuildNumber)
            $(Build.SourceBranchName)-$(Build.BuildNumber)
          arguments: '--build-arg PAT=$(PAT)'
      - task: Docker@2
        displayName: Build an image pos-profile
        inputs:
          containerRegistry: 'ado-2-acr-prd'
          repository: 'cxi-cdp-customer-profiles-pos-profile'
          command: 'build'
          Dockerfile: '**/Dockerfile'
          buildContext: '$(Build.SourcesDirectory)/src/'
          tags: |
            $(Build.BuildNumber)
            $(Build.SourceBranchName)-$(Build.BuildNumber)
          arguments: '--build-arg PAT=$(PAT)'
      - task: Docker@2
        displayName: Build an image user-profile
        inputs:
          containerRegistry: 'ado-2-acr-prd'
          repository: 'cxi-cdp-customer-profiles-user-profile'
          command: 'build'
          Dockerfile: '**/Dockerfile'
          buildContext: '$(Build.SourcesDirectory)/src/'
          tags: |
            $(Build.BuildNumber)
            $(Build.SourceBranchName)-$(Build.BuildNumber)
          arguments: '--build-arg PAT=$(PAT)'

      - task: Docker@2
        displayName: Push an image partner-profile
        condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))  
        inputs:
          containerRegistry: 'ado-2-acr-prd'
          repository: 'cxi-cdp-customer-profiles-partner-profile'
          command: 'push'
          tags: |
            $(Build.BuildNumber)
            $(Build.SourceBranchName)-$(Build.BuildNumber)
      - task: Docker@2
        displayName: Push an image pos-profile
        condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))  
        inputs:
          containerRegistry: 'ado-2-acr-prd'
          repository: 'cxi-cdp-customer-profiles-pos-profile'
          command: 'push'
          tags: |
            $(Build.BuildNumber)
            $(Build.SourceBranchName)-$(Build.BuildNumber)
      - task: Docker@2
        displayName: Push an image user-profile
        condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))  
        inputs:
          containerRegistry: 'ado-2-acr-prd'
          repository: 'cxi-cdp-customer-profiles-user-profile'
          command: 'push'
          tags: |
            $(Build.BuildNumber)
            $(Build.SourceBranchName)-$(Build.BuildNumber)

 - stage: deploy_prd
   condition: eq('${{ parameters.Environment }}', 'prd')
   dependsOn: Build
   displayName: Deploy to Kubernetes Prd
   jobs:
    - deployment: deploy
      displayName: Deploy
      variables:
      - group: common-prd
      environment: 'Kubernetes_Prd'
      strategy:
        runOnce:
          deploy:
            steps:
            - template: HelmDeploy.yaml@templates
              parameters:
                kubernetesServiceConnectionName: 'Kub_CXI_Cluster_PRD'
                namespace: 'customer-profiles'
                acrname: '$(registry)'
                azureservice: 'cxi-devops'
                acrrepo: 'cxi-default:20211129.2'
                chartPath: '$(build.stagingdirectory)/cxi-default/'
                components:
                - componentname: 'customer-profiles-partner-profile'
                  releasename: 'customer-profiles-partner-profile'
                  overridevalues: "
                    application.name=customer-profiles-partner-profile,\
                    application.env=prd,\
                    deployment.container.registry=$(registry),\
                    deployment.container.image.name=cxi-cdp-customer-profiles-partner-profile,\
                    deployment.container.image.tag=$(Build.BuildNumber),\
                    deployment.env.AZURE_APP_CONFIG=$(AZURE_APP_CONFIG),\
                    deployment.env.AZURE_KEY_VAULT_ID=$(AZURE_KEY_VAULT_ID),\
                    deployment.env.AZURE_KEY_VAULT_SECRET=$(AZURE_KEY_VAULT_SECRET),\
                    deployment.env.AZURE_KEY_VAULT_URL=$(AZURE_KEY_VAULT_URL),\
                    deployment.replicaCount=2,\
                    deployment.env.ASPNETCORE_ENVIRONMENT=$(ASPNETCORE_ENVIRONMENT)"
                - componentname: 'customer-profiles-pos-profile'
                  releasename: 'customer-profiles-pos-profile'
                  overridevalues: "
                    application.name=customer-profiles-pos-profile,\
                    application.env=prd,\
                    deployment.container.registry=$(registry),\
                    deployment.container.image.name=cxi-cdp-customer-profiles-pos-profile,\
                    deployment.container.image.tag=$(Build.BuildNumber),\
                    deployment.env.AZURE_APP_CONFIG=$(AZURE_APP_CONFIG),\
                    deployment.env.AZURE_KEY_VAULT_ID=$(AZURE_KEY_VAULT_ID),\
                    deployment.env.AZURE_KEY_VAULT_SECRET=$(AZURE_KEY_VAULT_SECRET),\
                    deployment.env.AZURE_KEY_VAULT_URL=$(AZURE_KEY_VAULT_URL),\
                    deployment.replicaCount=2,\
                    deployment.env.ASPNETCORE_ENVIRONMENT=$(ASPNETCORE_ENVIRONMENT)"    
                - componentname: 'customer-profiles-user-profile'
                  releasename: 'customer-profiles-user-profile'
                  overridevalues: "
                    application.name=customer-profiles-user-profile,\
                    application.env=prd,\
                    deployment.container.registry=$(registry),\
                    deployment.container.image.name=cxi-cdp-customer-profiles-user-profile,\
                    deployment.container.image.tag=$(Build.BuildNumber),\
                    deployment.env.AZURE_APP_CONFIG=$(AZURE_APP_CONFIG),\
                    deployment.env.AZURE_KEY_VAULT_ID=$(AZURE_KEY_VAULT_ID),\
                    deployment.env.AZURE_KEY_VAULT_SECRET=$(AZURE_KEY_VAULT_SECRET),\
                    deployment.env.AZURE_KEY_VAULT_URL=$(AZURE_KEY_VAULT_URL),\
                    deployment.replicaCount=2,\
                    deployment.env.ASPNETCORE_ENVIRONMENT=$(ASPNETCORE_ENVIRONMENT)"                       